### ISSUE TITLE
[Structural] Migrar a v14 l'Odoo de CE

### ISSUE THREAD

**Issue by juan-pe** [somcomunitats-coop/odoo-ec#10]
***In GitLab by @XavierBonetViura on Nov 23, 2022, 09:54 GMT+1:***

Els mantenidors del mòdul Societari han migrat ja el mòdul a la v14 (ells no fèien servir el Pypy) i el tenen integrat a la OCA "Cooperator" que a cada canvi de versió automàticament genera el paquei PyPy.
Hi ha companys de Coopdevs que estan revisant quins canvis han implementat.

Si ens quedem a la v12 (és una versió que està ja deprecada per odoo) i deixem escalar a la v14 per més envanant (quan ja tinguem CE's treballant-hi i molta més funcionalitat ja implementada) seà un esforç MOLT considerable comparat amb fer-ho ara. La v14 implica un canvi RADICAl a nivell comptable al Odoo rrespecte la v12 de manera que ens convé fer-ho i millor ara.

La Migració implicarà aprofitar el mòdul societari que je està a la v14 però haurem de migrar el **mòdul de costumitzacions de les CE** i el mòdul dela part de Odoo del **Community MAPS**

*Migrated from GitLab: https://git.coopdevs.org/coopdevs/comunitats-energetiques/odoo-ce/-/issues/10*

**Comment by juan-pe** [comment]
***In GitLab by @DaniilDigtyar on Dec 22, 2022, 10:47 GMT+1:***

**Requirements to migrate.**
- [x] ~~xmlsig==0.1.4~~ removed not needed anymore
- [X] odoo12-addon-account-asset-management==12.0.2.3.0.99.dev3  odoo14-addon-account-asset-management==14.0.2.8.0 
- [X] odoo12-addon-account-banking-mandate==12.0.2.0.0.99.dev7 odoo14-addon-account-banking-mandate==14.0.1.2.0 
- [x] odoo12-addon-account-banking-pain-base==12.0.1.0.1 odoo14-addon-account-banking-pain-base==14.0.1.0.2 
- [x] odoo12-addon-account-banking-sepa-credit-transfer==12.0.1.0.0.99.dev5 odoo14-addon-account-banking-sepa-credit-transfer==14.0.1.2.1
- [x] odoo12-addon-account-banking-sepa-direct-debit==12.0.1.1.0 odoo14-addon-account-banking-sepa-direct-debit==14.0.1.3.3
- [x] odoo12-addon-account-due-list==12.0.1.0.0.99.dev7 odoo14-addon-account-due-list==14.0.1.1.0
- [x] odoo12-addon-account-financial-report==12.0.1.2.1 odoo14-addon-account-financial-report==14.0.3.4.1
- [x] odoo12-addon-account-fiscal-year==12.0.1.0.0.99.dev6 odoo14-addon-account-fiscal-year==14.0.1.2.0
- [x] ~~odoo12-addon-account-group-menu==12.0.1.0.0.99.dev12~~ Merged to account_menu
- [X] odoo12-addon-account-invoice-check-total==12.0.1.1.0.99.dev11 odoo14-addon-account-invoice-check-total==14.0.1.0.1 REMOVED
- [X] odoo12-addon-account-invoice-force-number==12.0.1.0.0.99.dev11 odoo14-addon-account-invoice-force-number==14.0.1.0.1 REMOVED
- [X] odoo12-addon-account-invoice-refund-link==12.0.1.0.0.99.dev4 odoo14-addon-account-invoice-refund-link==14.0.1.0.3 REMOVED
- [x] odoo12-addon-account-lock-date-update==12.0.1.0.0.99.dev9 odoo14-addon-account-lock-date-update==14.0.2.0.1.dev8
- [x] odoo12-addon-account-payment-mode==12.0.1.0.0.99.dev14 odoo14-addon-account-payment-mode==14.0.1.1.0
- [x] odoo12-addon-account-payment-order==12.0.1.0.2 odoo14-addon-account-payment-order==14.0.1.11.0
- [x] odoo12-addon-account-payment-partner==12.0.1.0.0.99.dev13 odoo14-addon-account-payment-partner==14.0.1.6.0
- [x] odoo12-addon-account-payment-return==12.0.1.0.0.99.dev20 odoo14-addon-account-payment-return==14.0.1.0.5
- [x] odoo12-addon-account-payment-return-import==12.0.1.0.0.99.dev10 odoo14-addon-account-payment-return-import==14.0.1.0.3.dev1
- [x] odoo12-addon-account-payment-return-import-iso20022==12.0.1.1.0 odoo14-addon-account-payment-return-import-iso20022==14.0.1.0.1.dev2
- [x] odoo12-addon-account-payment-sale==12.0.1.1.0 odoo14-addon-account-payment-sale==14.0.1.0.1.dev14
- [x] odoo12-addon-account-tax-balance==12.0.1.1.0.99.dev5 odoo14-addon-account-tax-balance==14.0.1.2.6
- [X] ~~odoo12-addon-account-type-menu==12.0.1.0.0.99.dev7~~ -> Merged to account-menu https://redirect.github.com/OCA/account-financial-tools/pull/889
- [x] odoo12-addon-base-bank-from-iban==12.0.1.0.0.99.dev2 -> odoo14-addon-base-bank-from-iban==14.0.1.0.2.dev3
- [x] odoo12-addon-base-iso3166==12.0.1.0.0.99.dev4 -> odoo14-addon-base-iso3166==14.0.1.0.2.dev1
- [x] odoo12-addon-base-location==12.0.1.0.2.99.dev2 -> odoo14-addon-base-location==14.0.1.2.5.dev6
- [x] odoo12-addon-base-location-geonames-import==12.0.1.0.1 -> odoo14-addon-base-location-geonames-import==14.0.1.0.3.dev2
- [x] odoo12-addon-base-technical-features==12.0.1.0.0.99.dev11 -> odoo14-addon-base-technical-features==14.0.1.1.2.dev1
- [x] odoo12-addon-base-user-role==12.0.1.0.0.99.dev9 -> odoo14-addon-base-user-role==14.0.2.5.1
- [x] ~~odoo12-addon-currency-rate-update==12.0.1.1.2.99.dev3 -> odoo14-addon-currency-rate-update==14.0.1.2.1~~ removed not needed anymore
- [x] odoo12-addon-date-range==12.0.1.0.0.99.dev11 -> odoo14-addon-date-range==14.0.2.1.2.dev3
- [x] odoo12-addon-l10n-es-account-asset==12.0.2.0.6.99.dev4 -> odoo14-addon-l10n-es-account-asset==14.0.1.0.1.dev6
- [x] odoo12-addon-l10n-es-account-bank-statement-import-n43==12.0.1.0.3 -> odoo14-addon-l10n-es-account-statement-import-n43==14.0.1.0.4
- [x] odoo12-addon-l10n-es-account-banking-sepa-fsdd==12.0.1.0.0.99.dev4 -> odoo14-addon-l10n-es-account-banking-sepa-fsdd==14.0.1.0.1.dev5
- [ ] ~~odoo12-addon-l10n-es-account-invoice-sequence==12.0.1.0.1.99.dev5~~ Deprecated https://redirect.github.com/OCA/l10n-spain/pull/1208 Revisar com queda el tema i actualitzar la docu de configuració
- [x] odoo12-addon-l10n-es-aeat==12.0.2.3.0.99.dev6 odoo14-addon-l10n-es-aeat==14.0.2.4.2
- [X] git+https://redirect.github.com/coopdevs/l10n-spain@12.0-import-customer-facturae#egg=odoo12-addon-l10n-es-facturae&subdirectory=setup/l10n_es_facturae -> odoo14-addon-l10n-es-facturae==14.0.2.5.0 We now use the OCA standard
- [x] odoo12-addon-l10n-es-irnr==12.0.2.0.0.99.dev3 -> odoo14-addon-l10n-es-irnr==14.0.1.0.1 -> odoo14-addon-l10n-es-irnr==14.0.1.0.1 Module stays, but we are not 100% if we needed
- [x] odoo12-addon-l10n-es-mis-report==12.0.1.0.0.99.dev5 -> odoo14-addon-l10n-es-mis-report==14.0.1.3.2.dev1 -> odoo14-addon-l10n-es-mis-report==14.0.1.3.2.dev1
- [x] odoo12-addon-l10n-es-partner==12.0.1.0.2 -> odoo14-addon-l10n-es-partner==14.0.1.0.3.dev1
- [x] odoo12-addon-l10n-es-partner-mercantil==12.0.1.0.0.99.dev7 -> odoo14-addon-l10n-es-partner-mercantil==14.0.1.0.1.dev4
- [ ] odoo12-addon-l10n-es-toponyms==12.0.1.0.0.99.dev8 -> odoo14-addon-l10n-es-toponyms==14.0.1.0.1.dev4 Check if accents are applied in Spanish and Catalan
- [x] odoo12-addon-l10n-es-vat-book==12.0.1.6.2 -> odoo14-addon-l10n-es-vat-book==14.0.2.4.1.dev1
- [x] odoo12-addon-mail-tracking==12.0.1.1.3 -> odoo14-addon-mail-tracking==14.0.2.0.4.dev1
- [x] odoo12-addon-mass-editing==12.0.1.0.0.99.dev12 -> odoo14-addon-mass-editing==14.0.1.1.2
- [x] odoo12-addon-mis-builder==12.0.3.4.0.99.dev3 -> odoo14-addon-mis-builder==14.0.4.1.2.dev2
- [x] odoo12-addon-mis-builder-budget==12.0.3.3.0.99.dev1 -> odoo14-addon-mis-builder-budget==14.0.4.0.2.dev5
- [x] ~~odoo12-addon-mis-builder-demo==12.0.3.0.1.99.dev4 -> odoo14-addon-mis-builder-demo==14.0.3.1.4.dev1~~ Removed we don't need anymore
- [x] odoo12-addon-partner-external-map==12.0.1.0.0.99.dev6 -> odoo14-addon-partner-external-map==14.0.1.0.1.dev2 Community maps looks like doesn't use it so we remove it
- [x] odoo12-addon-partner-firstname==12.0.1.0.0.99.dev11 -> odoo14-addon-partner-firstname==14.0.1.1.1.dev4
- [x] odoo12-addon-report-py3o==12.0.2.0.2.99.dev18 -> odoo14-addon-report-py3o==14.0.1.0.3
- [x] odoo12-addon-report-xlsx==12.0.1.0.2 -> odoo14-addon-report-xlsx==14.0.1.0.10
- [x] odoo12-addon-web-advanced-search==12.0.1.0.0.99.dev10 -> odoo14-addon-web-advanced-search==14.0.1.0.2.dev3
- [x] odoo12-addon-web-decimal-numpad-dot==12.0.1.0.0.99.dev5 -> odoo14-addon-web-decimal-numpad-dot==14.0.1.0.1.dev2
- [x] odoo12-addon-web-environment-ribbon==12.0.1.0.0.99.dev16 -> odoo14-addon-web-environment-ribbon==14.0.1.0.1.dev8
- [x] ~~odoo12-addon-web-favicon==12.0.1.0.0.99.dev8~~ Merged to core https://redirect.github.com/OCA/web/issues/1388
- [x] odoo12-addon-web-no-bubble==12.0.1.0.0.99.dev4 -> odoo14-addon-web-no-bubble==14.0.1.0.1.dev3
- [x] odoo12-addon-web-responsive==12.0.1.3.2 -> odoo14-addon-web-responsive==14.0.1.2.1.dev12
- [X] ~~odoo12-addon-web-searchbar-full-width==12.0.1.0.0.99.dev3~~ Not migrated https://redirect.github.com/OCA/web/issues/1388
- [x] odoo12-addon-web-timeline==12.0.1.0.5.99.dev12 -> odoo14-addon-web-timeline==14.0.2.0.1.dev1
- [X] ~~odoo12-addon-web-widget-color==12.0.1.0.0.99.dev4~~ Merged to core https://redirect.github.com/OCA/OpenUpgrade/pull/2170
- [ ] odoo12-addon-web-widget-image-download==12.0.1.0.0.99.dev5 -> odoo14-addon-web-widget-image-download==14.0.1.0.1.dev4 Check why image is not showing
- [x] ~~odoo12-addon-web-widget-many2many-tags-multi-selection==12.0.1.0.0.99.dev3~~ Need to migrate web_widget_many2many_tags_multi_selection
- [x] ~~odoo12-addon-auth-keycloak==12.0.0.0.0~~ -> odoo14-addon-auth-oidc==14.0.1.0.3.dev1 Suspended to auth-oidc https://redirect.github.com/OCA/server-auth/issues/136
- [X] odoo12-addon-mass-mailing-list-dynamic==12.0.1.0.4 -> odoo14-addon-mass-mailing-list-dynamic==14.0.1.0.1.dev4
- [ ] odoo12-addon-community-maps==12.0.0.2.4 -> Need to migrate to 14.0
- [X] git+https://redirect.github.com/coopiteasy/vertical-cooperative@12.0#egg=odoo12-addon-easy-my-coop&subdirectory=setup/cooperator -> odoo14-addon-cooperator==14.0.1.5.2
- [X] git+https://redirect.github.com/coopiteasy/vertical-cooperative@12.0#egg=odoo12-addon-easy-my-coop-website&subdirectory=setup/cooperator_website -> odoo14-addon-cooperator-website==14.0.1.1.1
- [ ] git+https://redirect.github.com/coopiteasy/vertical-cooperative@12.0#egg=odoo12-addon-easy-my-coop-es&subdirectory=setup/l10n_es_cooperator -> Looks like it works in 14.0
- [ ] odoo12-addon-ce==12.0.0.0.14
- [x] python-slugify==5.0.2 -> Removed

NEW MODULES
- [x] odoo14-addon-base-user-role-company==14.0.2.0.1 To control user that are in multiple CE or coordinator and have different roles in them
- [X] odoo14-addon-auth-user-case-insensitive==14.0.1.0.1.dev3 To easier login with DNI
- [x] python-keycloak==2.9.0 To use in new API (removes dependency to the odoo module to interact with keycloak)
- [X] odoo14-addon-account-multicompany-easy-creation==14.0.1.0.1.dev2

**Comment by juan-pe** [comment]
***In GitLab by @DaniilDigtyar on Dec 29, 2022, 13:48 GMT+1:***

Add new module odoo14-addon-base-user-role-company to create roles specific for every company (CE).

I tried installing, but it appears to cause error with the field (in_group_22), can't find much information about the problem.
undefined

**Comment by juan-pe** [comment]
***In GitLab by @DaniilDigtyar on Dec 30, 2022, 09:54 GMT+1:***

I was able to fix it by deleting all users and assigning all access rights to admin user.

**Comment by juan-pe** [comment]
***In GitLab by @DaniilDigtyar on Feb 14, 2023, 17:45 GMT+1:***

mentioned in merge request odoo-ce-inventory!30

**Comment by juan-pe** [comment]
***In GitLab by @DaniilDigtyar on Mar 24, 2023, 14:12 GMT+1:***

I will close this issue as it is already migrated and in production.

[Trello card](https://trello.com/c/pB1CieTT/102-migraci%C3%B3-odoo-v12-v14)

**Comment by juan-pe** [comment]
***In GitLab by @enricostano on May 23, 2024, 19:56 GMT+2:***

unassigned @DaniilDigtyar
